### ISSUE TITLE
Executing hasura command opens new CMD console on Windows

### ISSUE THREAD

**Issue by uberpwner** [jjangga0214/hasura-cli#19]
### OS
Windows 10 

### Versions
hasura-cli: 1.0.0
Node: v12.13.1
npm: 6.13.4

### Description
Not sure if it's a bug or normal behaviour. When running hasura from any terminal other than CMD - it opens new CMD window, executes command and immediately closes. It is not very convenient in case you want to see the output. For example, when executing `hasura migrate status`

![final_5e0b1ed498f7ae0014c7103b_141885](https://user-images.githubusercontent.com/15633416/71618140-6cb13980-2bcf-11ea-98c4-4242cdbde496.gif)

### Reproduction
 - Install hasura-cli with `npm i -g hasura-cli`
 - Execute command `hasura version` from Powershell console

**Comment by jjangga0214** [comment]
@uberpwner 
Thank you for reporting this!

Every published version of `hasura-cli` passed [end-to-end test](https://github.com/jjangga0214/hasura-cli/blob/master/.github/workflows/nodejs.yml) on Windows 10 and Windows 2016. But only `CMD` was used during the tests. That might be why this behavior was not observed. 

I am not so familiar with Windows-specific behavior (`help wanted` label).
**So, I'd like to ask 2 things, if possible.**

Theoretically, this can be either a Powershell, node, npm, hasura cli, or Windows problem, or some caused by some complex combination. **To reduce possibility, if available, do you mind testing with another shell instead of CMD and Powershell (Though I don't know whether there is another kind)?** 

By the way, for you information, here's how `hasura-cli` works (in order) on Windows.

1. User(you) executes `hasura <arg>`.
1. `hasura` in `$PATH` is a symlink `npm` created when installed.
1. The symlink designates `your\global\node_modules\hasura-cli\bin\hasura`, as `hasura` is specified on `bin` in `package.json`.
1. `your\global\node_modules\hasura-cli\bin\hasura <arg>` is given to Windows.
1. Windows ignores `your\global\node_modules\hasura-cli\bin\hasura`, but executes `your\global\node_modules\hasura-cli\bin\hasura.exe`. (A dummy text file `hasura` and `hasura.exe` coexists. More detail in [hasura-cli#how-does-this-work](https://github.com/jjangga0214/hasura-cli#how-does-this-work))
1. Windows executes `your\global\node_modules\hasura-cli\bin\hasura.exe <arg>` 

**And secondly, would you please delete a dummy text file `your\global\node_modules\hasura-cli\bin\hasura`, and try again?**

Here's another question.
Have you(or someone) experienced a similar experienced with Powershell(or with something else) before? 

I will also look into why this happens.

Thank you again, for reporting the issue!

**Comment by uberpwner** [comment]
@jjangga0214 
First of all, I forgot to mention, that I have NVM v1.1.7 to switch between node versions, but I guess it's not relevant to this issue.

As for your questions, I got this results:

### Different shells:
I have 3 different shells, CMD, Powershell, and Git Bash.

Executing `where hasura` produces this output: 
```
C:\Program Files\nodejs\hasura
C:\Program Files\nodejs\hasura.cmd
```
Opening this path redirects me to `C:\Users\misha\AppData\Roaming\nvm\v12.13.1`, where I found 3 files: **hasura** (bash script), **hasura.cmd** (cmd script) and **hasura.ps1** (powershell script).
I tryed calling them all from all shells. Here are the results:

- CMD:
  - `hasura version` outputs version
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` opens file in notepad
- Powershell:
  - `hasura version` opens CMD window, executes command and immediately closes
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` opens CMD window, executes command and immediately closes
- Git Bash:
  - `hasura version` looks like is trying to execute dummy text file. Outputs
    ```
    C:\Program Files\nodejs/node_modules/hasura-cli/hasura: line 1: This: command not found
    C:\Program Files\nodejs/node_modules/hasura-cli/hasura: line 2: The: command not found
    C:\Program Files\nodejs/node_modules/hasura-cli/hasura: line 3: So,: command not found
    C:\Program Files\nodejs/node_modules/hasura-cli/hasura: line 4: and: command not found
    ```
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` outputs `/usr/bin/env: ‘pwsh’: No such file or directory`

### Removed dummy text file
- CMD: 
  - `hasura version` outputs version
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` opens file in notepad
- Powershell:
  - `hasura version` **now outputs version**
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` **now outputs version**
- Git Bash:
  - `hasura version` **now outputs version**
  - `hasura.cmd version` outputs version
  - `hasura.ps1 version` outputs `/usr/bin/env: ‘pwsh’: No such file or directory`

So it looks like removing dummy file solves this issue in all shells available to me.

### Question about similar experience
No, I have never experienced or heard of such behaviour.

If you need to check more details on Windows environment - I'll be happy to help.

**Comment by jjangga0214** [comment]
@uberpwner This information is very helpful 👍
I'll patch and test if it then really works on Windows :)
The next release will have the patch.
Thanks a lot :)

**Comment by voraczech** [comment]
My solution for bash (in case someone still needs it, I have problems with versions 1.3.1/1.3.2):

1) find your `hasura` file path

```bash
where hasura
```

2) Open `hasura` file (not `hasura.cmd`). You should see this:

```bash
"$basedir/node_modules/hasura-cli/hasura"   "$@"
exit $?
```

3) Replace it with this:

```bash
"$(dirname "$0")/node_modules/hasura-cli/hasura"   "$@"
exit $?
```

I am not a bash expert, so any improvement will be welcomed. Though, this works for me well, so it could help somebody else.
