### ISSUE TITLE
Which files to .gitignore?

### ISSUE THREAD

**Issue by holloway** [jjangga0214/hasura-cli#60]
Not sure if this is the right repo for this, but when I install Hasura CLI and set up a project with migration it generates some files.

One of them is `metadata/databases/databases.yaml` which includes a connection string with a password in it.

I'd prefer not to check this into Git but which files should I check in or not?

**Comment by zenflow** [comment]
These generated files should all be checked in, but you obviously don't want that to include your db password, so, instead of setting up the db connection to use the connection string directly, put the connection string in an environment variable and have your db connection use that environment variable. You can see the option when you create the db connection in the Hasura Console.
